"""empty message

Revision ID: 028d4aa764ba
Revises: 
Create Date: 2024-09-22 03:52:26.789770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '028d4aa764ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('featured_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('featured_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('featured_id')
    )
    op.drop_table('special_feature')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'feature', ['prod_featured_id'], ['featured_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('special_feature',
    sa.Column('special_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('special_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('special_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('feature')
    # ### end Alembic commands ###
