"""empty message

Revision ID: 3c43178e4e80
Revises: 77dbe2883d31
Create Date: 2024-10-22 14:45:58.272102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c43178e4e80'
down_revision = '77dbe2883d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_reference', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['order_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_reference')

    # ### end Alembic commands ###
