"""empty message

Revision ID: 77dbe2883d31
Revises: c298898ed512
Create Date: 2024-09-24 12:35:25.925103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77dbe2883d31'
down_revision = 'c298898ed512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('pay_email')
        batch_op.create_unique_constraint(None, ['pay_reference'])
        batch_op.drop_column('pay_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('pay_email', ['pay_email'], unique=True)

    # ### end Alembic commands ###
