"""empty message

Revision ID: bcca8affa14d
Revises: 028d4aa764ba
Create Date: 2024-09-23 10:09:28.105059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcca8affa14d'
down_revision = '028d4aa764ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ord_item_total_amt', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('ord_total_amt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ord_total_amt', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('ord_item_total_amt')

    # ### end Alembic commands ###
