"""empty message

Revision ID: c298898ed512
Revises: bcca8affa14d
Create Date: 2024-09-23 21:49:04.924871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c298898ed512'
down_revision = 'bcca8affa14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_ship_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shipping', ['order_ship_id'], ['ship_id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_3', type_='foreignkey')
        batch_op.drop_column('ord_item_ship_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ord_item_ship_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_item_ibfk_3', 'shipping', ['ord_item_ship_id'], ['ship_id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_ship_id')

    # ### end Alembic commands ###
