"""empty message

Revision ID: c4a94c8d4744
Revises: 60b246fd45df
Create Date: 2024-10-25 17:01:23.016841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a94c8d4744'
down_revision = '60b246fd45df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_reference', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['order_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_reference')

    # ### end Alembic commands ###
